# Generated by Django 4.2.6 on 2023-10-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0002_second'),
    ]

    operations = [
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name0', models.CharField(max_length=250)),
                ('img0', models.ImageField(upload_to='pics')),
                ('desc0', models.TextField()),
            ],
        ),
    ]
